#!/usr/bin/env php
<?php

/*
 * Fetches merged pull requests authored by ktherage on third-party public
 * repositories and writes them to data/oss-contributions.yaml (single file).
 *
 * Source: GitHub Search API (GET /search/issues?q=author:ktherage+type:pr+is:merged).
 * Auth: optional GITHUB_TOKEN env var (higher rate limits); works anonymously.
 *
 * This script must NEVER fail the build: on any error it writes an empty
 * list and exits 0. The layout renders a graceful empty state in that case.
 *
 * Usage: php scripts/fetch-oss-contributions.php
 */
declare(strict_types=1);

require __DIR__.'/../vendor/autoload.php';

use Symfony\Component\HttpClient\HttpClient;
use Symfony\Component\Yaml\Yaml;

const OSS_USERNAME = 'ktherage';
const OSS_OUTPUT = __DIR__.'/../data/oss-contributions.yaml';
const OSS_PER_PAGE = 100;
const OSS_MAX_PAGES = 3;

function oss_write_empty(string $reason): void
{
    fwrite(STDERR, 'OSS fetch: '.$reason." — writing empty list.\n");
    file_put_contents(OSS_OUTPUT, "[]\n");
}

$headers = ['Accept: application/vnd.github+json', 'User-Agent: ktherage.github.io-oss-fetch'];
$token = getenv('GITHUB_TOKEN');
if (false !== $token && '' !== $token) {
    $headers[] = 'Authorization: Bearer '.$token;
}
$client = HttpClient::create(['headers' => $headers, 'timeout' => 20]);

$items = [];
try {
    for ($page = 1; $page <= OSS_MAX_PAGES; ++$page) {
        $response = $client->request('GET', 'https://api.github.com/search/issues', [
            'query' => [
                'q' => 'author:'.OSS_USERNAME.' type:pr is:merged',
                'sort' => 'updated',
                'order' => 'desc',
                'per_page' => OSS_PER_PAGE,
                'page' => $page,
            ],
        ]);
        $data = $response->toArray();
        if (!isset($data['items']) || !is_array($data['items'])) {
            oss_write_empty('unexpected API response');
            exit(0);
        }
        foreach ($data['items'] as $pr) {
            $parts = explode('/', (string) ($pr['repository_url'] ?? ''));
            if (count($parts) < 2) {
                continue;
            }
            [$owner, $repo] = [$parts[count($parts) - 2], $parts[count($parts) - 1]];
            if (0 === strcasecmp($owner, OSS_USERNAME)) {
                continue; // own repositories are not "contributions"
            }
            $mergedAt = (string) (($pr['pull_request'] ?? [])['merged_at'] ?? '');
            if ('' === $mergedAt) {
                continue;
            }
            $items[] = [
                'title' => (string) ($pr['title'] ?? ''),
                'url' => (string) ($pr['html_url'] ?? ''),
                'repo' => $owner.'/'.$repo,
                'repo_url' => 'https://github.com/'.$owner.'/'.$repo,
                'avatar' => 'https://github.com/'.$owner.'.png',
                'merged_at' => substr($mergedAt, 0, 10),
            ];
        }
        if (count($data['items']) < OSS_PER_PAGE) {
            break;
        }
    }
} catch (Throwable $e) {
    oss_write_empty($e->getMessage());
    exit(0);
}

$yaml = "# Generated by scripts/fetch-oss-contributions.php — do not edit by hand.\n";
$yaml .= Yaml::dump($items, 2, 2);
file_put_contents(OSS_OUTPUT, $yaml);
fwrite(STDERR, sprintf("OSS fetch: wrote %d contribution(s) to %s\n", count($items), OSS_OUTPUT));
exit(0);
